<?php

declare(strict_types=1);

namespace IndicScriptConverter\Verification;

/** Index-aligned Latin/IAST verification corpus ported from the Dart/Python source. */
const TRANSLITERATION_SMOKE_SAMPLES = [
    'Kṛṣṇa',
    'Śiva',
    'Rāma',
    'vrata',
    'jñāna',
    'yajña',
    'kṣetra',
    'Gaṅgā',
    'Śrīmad Bhāgavatam',
    'saṃskāra',
    'saṃkalpa',
    'Saṃskṛta',
    'Siṃha',
    'Pāṇḍava',
    'Lakṣmaṇa',
    'Hṛṣīkeśa',
    'pañcāṅga',
    'candra',
    'Kathā',
    'Pūjā',
    'Māyā',
    'Aśvattha',
    'Sūrya',
    'Dharma',
    'oṃ',
    'ṛṣi',
    "so'ham",
    'Hare Kṛṣṇa, Rāma-Rāma!',
    'Kr̥ṣṇa',
    'rāma',
    'kṛṣṇa',
    'śiva',
    'lakṣmaṇa',
    'saṃskṛta',
    'Aum',
    'baḷa',
    'dharma-kṣetra',
    'qaumī ġazal faḍa',
    'awśika',
    'uueśa',
    'oṃ namaḥ śivāya',
    'duḥkha',
    'antaḥkaraṇa',
    'niḥśvāsa',
    'duḥśāsana',
    'saṃsāra',
    'saṃyoga',
    'saṃvāda',
    'siṃha',
    'saṃhitā',
    'aṃśa',
    'saṃshaya',
    'saṅkalpa',
    'sañcaya',
    'khaṇḍa',
    'daṇḍa',
    'sattva',
    'tattva',
    'mahattva',
    'buddhi',
    'śuddhi',
    'mantra',
    'yantra',
    'kārtikeya',
    'mūrti',
    'kīrtana',
    'prakṛti',
    'vikrama',
    'cakra',
    'vajra',
    'agra',
    'nigraha',
    'pratiṣṭhā',
    'adhiṣṭhāna',
    'niṣṭhā',
    'utkṣepa',
    'saṅkṣepa',
    'sākṣī',
    'dīkṣā',
    'mokṣa',
    'vṛkṣa',
    'pakṣa',
    'sūkṣma',
    'tīkṣṇa',
    'dhyāna',
    'adhyāya',
    'madhya',
    'vidyā',
    'uddyoga',
    'paryaṅka',
    'ārya',
    'kārya',
    'vīrya',
    'sva',
    'svara',
    'svapna',
    'śvāsa',
    'īśvara',
    'aiśvarya',
    'dhvaja',
    'pakva',
    'vākya',
    'satya',
    'nitya',
    'mṛtyu',
    'bhrātṛ',
    'pitṛ',
    'mātṛ',
    'dātṛ',
    'bhrātr̥',
    'mitra',
    'citra',
    'putra',
    'rāṣṭra',
    'śāstra',
    'astra',
    'yajñopavīta',
    'vijñāna',
    'ājñā',
    'prājña',
    'yajñeśvara',
    'jñātṛ',
    'agni',
    'vighna',
    'cihna',
    'brāhmaṇa',
    'brahman',
    'vahni',
    'jihvā',
    'gṛhṇa',
    'uṣṇa',
    'viṣṇu',
    'vaiṣṇava',
    'kārtsnya',
    'autsukya',
    'mātsarya',
    'gau',
    'nau',
    'vai',
    'kau',
    'aupaniṣada',
    'aihikā',
    'audārya',
    'ṛṇam',
    'ṝṇa',
    'ḷkāra',
    'ḹkāra',
    'ṛtam',
    'ṛddhi',
    'ṛṣabha',
    'kḷpta',
    'dṛṣṭi',
    'sṛṣṭi',
    'vṛddha',
    'cā̐da',
    'mā̐',
    "te'pi",
    "sa'pi",
    'sā\'dhvī',
    'tathā\'pi',
    'cā\'haṁ',
    'ŚrīmadBhagavadGītā',
    'saccidānanda',
    'sadānanda',
    'paramānanda',
    'brahmānanda',
    'RādhāKṛṣṇa',
    'ŚivaLiṅga',
    'nārāyaṇa',
    'nārāyaṇīya',
    'mahābhārata',
    'rāmāyaṇa',
    'vālmīki',
    'vyāsa',
    'pārvatī',
    'gaṇapati',
    'gaṇeśa',
    'durgā',
    'kālī',
    'sarasvatī',
    'lakṣmī',
    'pārvatīpati',
    'umāmaheśvara',
    'nandikeśvara',
    'viśvanātha',
    'jagannātha',
    'raghunātha',
    'sītārāma',
    'rādhāramaṇa',
    'govinda',
    'gopāla',
    'mādhava',
    'keśava',
    'vāsudeva',
    'sarvottama',
    'nirguṇa',
    'saguṇa',
    'nirākāra',
    'sākāra',
    'nirvikalpa',
    'savikalpa',
    'aham',
    'aham̐',
    'brahma',
    'brahmā',
    'brahmaṇe',
    'brahmaṇaḥ',
    'ātma',
    'ātmanaḥ',
    'paramātma',
    'paramātmā',
    'jīvātma',
    'jīvātmā',
    'Om̐',
    'Oṁ',
    'oṁ',
    'śrīḥ',
    'guruḥ',
    'bhagavān',
    'mahān',
    'rājan',
    'ātman',
    'antaryāmitva',
    'vyavahārika',
    'pāramārthika',
    'ādhidaivika',
    'ādhibhautika',
    'ādhyātmika',
    'prātibhāsika',
    'vaiśeṣika',
    'sāṅkhyayoga',
    'aṣṭāṅgayoga',
    'haṭhayoga',
    'rājayoga',
    'karmayoga',
    'bhaktiyoga',
    'jñānayoga',
    'dhyānayoga',
    'prāṇāyāma',
    'pratyāhāra',
    'dhāraṇā',
    'samādhi',
    'samādhī',
    'putrāya',
    'putrasya',
    'putreṇa',
    'putrebhyaḥ',
    'putrāṇām',
    'putreṣu',
    'nadyām',
    'nadyāḥ',
    'gurave',
    'guroḥ',
    'munayaḥ',
    'munīnām',
    'munibhiḥ',
    'phalam',
    'phalāni',
    'phaleṣu',
    'Śiva',
    'Rāma',
    'śānti',
    'kr̥ṣṇa',
    'Kṛṣṇa said "namaste" to Arjuna',
    '123 Kṛṣṇa 456',
    "Kṛṣṇa\nRāma",
    '  Śiva   ',
    '',
    'a',
    'ā',
    'kṛtsna',
    'tryambaka',
    'sāṁkhya',
    'sāṃkhya',
    'Upaniṣad',
    'upaniṣat',
    'jagat',
    'vāri',
    'madhu',
    'manāṁsi',
    'havīṁṣi',
    'ekādaśa',
    'dvādaśa',
    'trayodaśa',
    'caturdaśa',
    'pañcadaśa',
    'ṣoḍaśa',
    'saptadaśa',
    'aṣṭādaśa',
    'ūnaviṃśati',
    'viṃśati',
    'triṃśat',
    'catvāriṃśat',
    'pañcāśat',
    'ṣaṣṭi',
    'saptati',
    'aśīti',
    'navati',
    'śatam',
    'sahasram',
    'ayutam',
    'niyutam',
    'prayutam',
    'koṭi',
    'namaḥ',
    'svāhā',
    'vaṣaṭ',
    'svadhā',
    'oṁ namaḥ śivāya',
    'oṁ namo nārāyaṇāya',
    'hariḥ oṁ',
    'śāntiḥ śāntiḥ śāntiḥ',
    'śraddhā',
    'kriyā',
    'upādhyāya',
    'anugraha',
    'saṃjñā',
    'vidyālaya',
    'bhāratīya',
    'rājya',
    'kāvya',
    'śikṣā',
    'śikṣaka',
    'saṃskṛti',
    'bhakti',
    'śakti',
    'mahimā',
    'udyoga',
    'tyāga',
    'upayoga',
    'ĕka',
    'ăgama',
    'êka',
    'ĕkānta',
    'ŏjas',
    'ŏmka',
    'kævalya',
    'koeśa',
    'kōeśvara',
    'kooeśa',
    'kawśika',
    'kueśa',
    'kūeśa',
    'kuueśa',
    'ê̄śa',
    'ā̂tman',
    'a̍gni',
    'a̎nna',
    'a̱tman',
    'a̲nanta',
    'ăgama',
    'ĕkānta',
    'ŏmka',
    'ṉāda',
    'ṟāja',
    'ḻīlā',
    'ġaṇa',
    'ǧana',
    'žaṭa',
    'ẏajña',
    'ʔāgama',
    'ɗaṇḍa',
    'ɓakti',
    'k͟haṇḍa',
    'xaṇḍa',
    'ḫāna',
    'ƞaṭa',
    'ŋaṇa',
    'ħaṭha',
    'ẖara',
    'ḏharma',
    'ṯīkā',
    'ḳarma',
    'ẓamāna',
    'ṡakti',
    'ṙṣi',
    'ḍḍa',
    'yyaśa',
    'ggaṇa',
    'jjaṭa',
    'ṝṣi',
    'ḹka',
    'ṣ́akti',
    'śaṅkara',
    'ñāna',
    'ṁaṅgala',
    'ṃ̄',
    'ā̐nanda',
    'a̐̄nanda',
    'ōṃkāra',
    'ḥṛdaya',
    'ḵṣetra',
    'g̱aṇeśa',
    'żikr',
    'ṝṣi',
    'ṝṣi',
    'ḹka',
    'ḹka',
    'ṣ́akti',
    'śaṅkara',
    'ñāna',
    'ṁaṅgala',
    'ṃ̄',
    'ā̐nanda',
    'ōṃkāra',
    'ḥṛdaya',
    'ḵṣetra',
    'żikr',
    'ṛaka',
    'ṛhaṇa',
    'ṟāma',
    'ẏogin',
    'žaṇa',
    'xaiva',
    'k͟hāna',
    'ġaurī',
    'ǧñāna',
    'ḻakṣmī',
    'agním',
    'agnìm',
    'sómā',
    'prāṇá',
    'ṛ̀ta',
    'ṛ́ṣi',
    'ā́tman',
    'ū̀rjā',
    'ḷ́kāra',
    'm̐tra',
    'façade-mantra',
    'piñata-yajña',
    'São-saṃskāra',
    'naïve-vedānta',
    'œuvre-yoga',
    'smørrebrød-śāstra',
    'Łódź-kṣetra',
    'straße-dharma',
    'Þora-tantra',
    'ðarma-śāstra',
    'śrī-kṛṣṇa',
    'śrī/kṛṣṇa',
    'śrī.kṛṣṇa',
    'śrī,kṛṣṇa',
    'śrī:kṛṣṇa',
    'śrī;kṛṣṇa',
    '(kṛṣṇa)',
    '[śiva]',
    '{rāma}',
    '"gītā"',
    '\'jñāna\'',
    '...saṃsāra...',
    'kṛṣṇa—rāma',
    'śiva–śakti',
    'oṁ/śāntiḥ/śāntiḥ',
    'te\'pi, sa\'pi, tathā\'pi',
    'KṚṢṆA',
    'ŚRĪMADBHAGAVADGĪTĀ',
    'JÑĀNAYOGA',
    'KĔŚAVA',
    'KǦAṆA',
    'KƊA',
    'KƁA',
    'OṂ NAMAḤ ŚIVĀYA',
    'sarvajñātmabhāva',
    'paramārthasatya',
    'śabdānuśāsana',
    'adhyavasāya',
    'anirvacanīyatā',
    'prajñāpāramitā',
    'mahāvākyārtha',
    'sarvasaṃskārānityatā',
    'duḥkhānupaśyanā',
    'caitanyamātra',
    'svātantryaśakti',
    'śāstrārthavicāra',
    'brahmavidyārṇava',
    'ìṣe tvòrje tvā́ vā̀yavá stha dèvo váḥ savìtā prārpáyatù śreṣṭhátamāyà karmáṇà āpyā́yadhva maghnyā̀ indrā́ya bhā̀gaṃ pràjāvátīranamī̀vā áyàkṣmā mā vá stèna ī́śatà māghaśám̐so dhrùvā àsmin gopátau syāta bàhvīryajámānasya pàśūnpā́hi || 1 ||',
    'vasóḥ pàvitrámasì dyaúrasi pṛthìvyàsi mātàriśváno ghàrmò\'si vìśvadhā́ asi |',
    'paràmeṇà dhāmnā̀ dṛm̐hásvà mā hvā̀rmā té yàjñapátirhvārṣīt || 2 ||',
    'vasóḥ pàvitrámasi śàtadhā́raṁ̀ vasóḥ pàvitrámasi sàhasrádhāram |',
    'dèvastvā́ savìtā púnātù vasóḥ pàvitréṇa śàtadhā́reṇa sùpvā kāmádhukṣaḥ || 3 ||',
    'sā vìśvāyùḥ sā vìśvakármā̀ sā vìśvadhā́yāḥ |',
    'indrásya tvā bhā̀gam̐ somènātánacmì viṣṇó hàvyam̐ rákṣa || 4 ||',
    'agné vratapate vràtaṃ cáriṣyāmì tacchákeyaṁ̀ tanmé rādhyatām | ìdamàhamanṛ́tātsàtyamupaími || 5 ||',
    'kastvā́ yunaktì sa tvā́ yunaktì kasmaí tvā yunaktì tasmaí tvā yunakti | karmáṇe vāṁ̀ veṣā́ya vām || 6 ||',
    'pratyúṣṭàm̐ rakṣàḥ pratyúṣṭā̀ arā́tayò niṣṭáptàm̐ rakṣò niṣṭáptā̀ arā́tayaḥ | ùrvantaríkṣàmanvémi || 7 ||',
    'dhūrásì dhūrvà dhūrvántaṁ̀ dhūrvà taṃ yò\'smāndhūrvátì taṃ dhū́rvà yaṃ vàyaṃ dhūrvā́maḥ |',
    'dèvānā́masì vahnítamàm̐ sasnítamaṁ̀ paprítamaṁ̀ juṣṭátamaṃ devàhūtámam || 8 ||',
    'viṣṇústvā kramatā¬mùru vātā̀yāpáhatàm̐ rakṣò yacchántāṁ̀ pañcá || 9 ||',
    'dèvasyá tvā savìtuḥ prásàve\'śvinórbā̀hubhyāṃ́ pū̀ṣṇo hastā́bhyām |',
    'àgnayè juṣṭáṃ gṛhṇāmyàgnīṣomā́bhyāṁ̀ juṣṭáṃ gṛhṇāmi || 10 ||',
    'bhū̀tāyá tvā̀ nārā́taye svàrabhìvikhyéṣaṁ̀ dṛm̐hántāṁ̀ duryā́ḥ pṛthìvyāmùrvantaríkṣàmanvémi pṛthìvyāstvā̀ nābhaú sādayā̀myadítyā ùpasthe\'gné hàvyam̐ rákṣa || 11 ||',
    'pàvitré stho vaiṣṇàvyaù savìturváḥ prasàva utpúnā̀myacchídreṇa pàvitréṇà sūryásya ràśmibhíḥ |',
    'devī́rāpo agreguvo agrepùvo\'grá ìmamàdya yàjñaṃ náyàtāgré yàjñapátim̐ sùdhātúṃ yàjñapátiṃ devàyuvám || 12 ||',
    'yùṣmā indró\'vṛṇīta vṛtràtūryé yū̀yamindrámavṛṇīdhvaṃ vṛtràtūryè prokṣítā stha |',
    'àgnayé tvā̀ juṣṭaṃ̀ prokṣā́myàgnīṣomā́bhyāṃ tvā̀ juṣṭaṃ̀ prokṣā́mi |',
    'daivyā́yà karmáṇe śundhadhvaṃ devayàjyāyaì yadvo\'śúddhāḥ parājàghnurìdaṃ vàstacchúndhāmi || 13 ||',
    'śarmā̀syavádhūtàm̐ rakṣo\'vádhūtā̀ arā́tàyo \'dítyā̀stvagásì pratì tvādítirvettu | adrírasi vānaspàtyo grāvā́\'si pṛ̀thubúdhnàḥ pratì tvā\'dítyā̀stvagvéttu || 14 ||',
];

/** @var list<array{0:string,1:string,2:string}> */
const VEDIC_ROUND_TRIP_CASES = [
    ['ìṣe tvòrje tvā́ vā̀yavá stha dèvo váḥ savìtā prārpáyatù śreṣṭhátamāyà karmáṇà āpyā́yadhva maghnyā̀ indrā́ya bhā̀gaṃ pràjāvátīranamī̀vā áyàkṣmā mā vá stèna ī́śatà māghaśám̐so dhrùvā àsmin gopátau syāta bàhvīryajámānasya pàśūnpā́hi || 1||', 'इ॒षे त्वो॒र्जे त्वा॑ वा॒यव॑ स्थ दे॒वो वः॑ सवि॒ता प्रार्प॑यतु॒ श्रेष्ठ॑तमाय॒ कर्म॑ण॒ आप्या॑यध्व मघ्न्या॒ इन्द्रा॑य भा॒गं प्र॒जाव॑तीरनमी॒वा अ॑य॒क्ष्मा मा व॑ स्ते॒न ई॑शत॒ माघशᳪ॑सो ध्रु॒वा अ॒स्मिन् गोप॑तौ स्यात ब॒ह्वीर्यज॑मानस्य प॒शून्पा॑हि ।। १।।', 'Mantra 1'],
    ['vasóḥ pàvitrámasì dyaúrasi pṛthìvyàsi mātàriśváno ghàrmò\'si vìśvadhā́ asi |', 'वसोः॑ प॒वित्र॑मसि॒ द्यौ॑रसि पृथि॒व्य॒सि मात॒रिश्व॑नो घ॒र्मो॒ऽसि वि॒श्वधा॑ असि ।', 'Mantra 2a'],
    ['paràmeṇà dhāmnā̀ dṛm̐hásvà mā hvā̀rmā té yàjñapátirhvārṣīt || 2 ||', 'पर॒मेण॒ धाम्ना॒ दृᳪह॑स्व॒ मा ह्वा॒र्मा ते॑ य॒ज्ञप॑तिर्ह्वार्षीत् ।। २ ।।', 'Mantra 2b'],
    ['vasóḥ pàvitrámasi śàtadhā́raṁ̀ vasóḥ pàvitrámasi sàhasrádhāram |', 'वसोः॑ प॒वित्र॑मसि श॒तधा॑रं॒ वसोः॑ प॒वित्र॑मसि स॒हस्र॑धारम् ।', 'Mantra 3a'],
    ['dèvastvā́ savìtā púnātù vasóḥ pàvitréṇa śàtadhā́reṇa sùpvā kāmádhukṣaḥ || 3 ||', 'दे॒वस्त्वा॑ सवि॒ता पु॑नातु॒ वसोः॑ प॒वित्रे॑ण श॒तधा॑रेण सु॒प्वा काम॑धुक्षः ।। ३ ।।', 'Mantra 3b'],
    ['sā vìśvāyùḥ sā vìśvakármā̀ sā vìśvadhā́yāḥ |', 'सा वि॒श्वायुः॒ सा वि॒श्वक॑र्मा॒ सा वि॒श्वधा॑याः ।', 'Mantra 4a'],
    ['indrásya tvā bhā̀gam̐ somènātánacmì viṣṇó hàvyam̐ rákṣa || 4 ||', 'इन्द्र॑स्य त्वा भा॒गᳪ सोमे॒नात॑नच्मि॒ विष्णो॑ ह॒व्यᳪ र॑क्ष ।। ४ ।।', 'Mantra 4b'],
    ['agné vratapate vràtaṃ cáriṣyāmì tacchákeyaṁ̀ tanmé rādhyatām | ìdamàhamanṛ́tātsàtyamupaími || 5 ||', 'अग्ने॑ व्रतपते व्र॒तं च॑रिष्यामि॒ तच्छ॑केयं॒ तन्मे॑ राध्यताम् । इ॒दम॒हमनृ॑तात्स॒त्यमुपै॑मि ।। ५ ।।', 'Mantra 5'],
    ['kastvā́ yunaktì sa tvā́ yunaktì kasmaí tvā yunaktì tasmaí tvā yunakti | karmáṇe vāṁ̀ veṣā́ya vām || 6 ||', 'कस्त्वा॑ युनक्ति॒ स त्वा॑ युनक्ति॒ कस्मै॑ त्वा युनक्ति॒ तस्मै॑ त्वा युनक्ति । कर्म॑णे वां॒ वेषा॑य वाम् ।। ६ ।।', 'Mantra 6'],
    ['pratyúṣṭàm̐ rakṣàḥ pratyúṣṭā̀ arā́tayò niṣṭáptàm̐ rakṣò niṣṭáptā̀ arā́tayaḥ | ùrvantaríkṣàmanvémi || 7 ||', 'प्रत्यु॑ष्टᳪ॒ रक्षः॒ प्रत्यु॑ष्टा॒ अरा॑तयो॒ निष्ट॑प्तᳪ॒ रक्षो॒ निष्ट॑प्ता॒ अरा॑तयः । उ॒र्वन्तरि॑क्ष॒मन्वे॑मि ।। ७ ।।', 'Mantra 7'],
    ['dhūrásì dhūrvà dhūrvántaṁ̀ dhūrvà taṃ yò\'smāndhūrvátì taṃ dhū́rvà yaṃ vàyaṃ dhūrvā́maḥ |', 'धूर॑सि॒ धूर्व॒ धूर्व॑न्तं॒ धूर्व॒ तं यो॒ऽस्मान्धूर्व॑ति॒ तं धू॑र्व॒ यं व॒यं धूर्वा॑मः ।', 'Mantra 8a'],
    ['dèvānā́masì vahnítamàm̐ sasnítamaṁ̀ paprítamaṁ̀ juṣṭátamaṃ devàhūtámam || 8 ||', 'दे॒वाना॑मसि॒ वह्नि॑तमᳪ॒ सस्नि॑तमं॒ पप्रि॑तमं॒ जुष्ट॑तमं देव॒हूत॑मम् ।। ८ ।।', 'Mantra 8b'],
    ['viṣṇústvā kramatā¬mùru vātā̀yāpáhatàm̐ rakṣò yacchántāṁ̀ pañcá || 9 ||', 'विष्णु॑स्त्वा क्रमता¬मु॒रु वाता॒याप॑हतᳪ॒ रक्षो॒ यच्छ॑न्तां॒ पञ्च॑ ।। ९ ।।', 'Mantra 9'],
    ['dèvasyá tvā savìtuḥ prásàve\'śvinórbā̀hubhyāṃ́ pū̀ṣṇo hastā́bhyām |', 'दे॒वस्य॑ त्वा सवि॒तुः प्र॑स॒वेऽश्विनो॑र्बा॒हुभ्यां॑ पू॒ष्णो हस्ता॑भ्याम् ।', 'Mantra 10a'],
    ['àgnayè juṣṭaṃ́ gṛhṇāmyàgnīṣomā́bhyāṃ̀ juṣṭaṃ́ gṛhṇāmi || 10 ||', 'अ॒ग्नये॒ जुष्टं॑ गृह्णाम्य॒ग्नीषोमा॑भ्यां॒ जुष्टं॑ गृह्णामि ।। १० ।।', 'Mantra 10b'],
    ['bhū̀tāyá tvā̀ nārā́taye svàrabhìvikhyéṣaṁ̀ dṛm̐hántāṁ̀ duryā́ḥ pṛthìvyāmùrvantaríkṣàmanvémi pṛthìvyāstvā̀ nābhaú sādayā̀myadítyā ùpasthe\'gné hàvyam̐ rákṣa || 11 ||', 'भू॒ताय॑ त्वा॒ नारा॑तये स्व॒रभि॒विख्ये॑षं॒ दृᳪह॑न्तां॒ दुर्याः॑ पृथि॒व्यामु॒र्वन्तरि॑क्ष॒मन्वे॑मि पृथि॒व्यास्त्वा॒ नाभौ॑ सादया॒म्यदि॑त्या उ॒पस्थेऽग्ने॑ ह॒व्यᳪ र॑क्ष ।। ११ ।।', 'Mantra 11'],
    ['pàvitré stho vaiṣṇàvyaù savìturváḥ prasàva utpúnā̀myacchídreṇa pàvitréṇà sūryásya ràśmibhíḥ |', 'प॒वित्रे॑ स्थो वैष्ण॒व्यौ॒ सवि॒तुर्वः॑ प्रस॒व उत्पु॑ना॒म्यच्छि॑द्रेण प॒वित्रे॑ण॒ सूर्य॑स्य र॒श्मिभिः॑ ।', 'Mantra 12a'],
    ['devī́rāpo agreguvo agrepùvo\'grá ìmamàdya yàjñaṃ náyàtāgré yàjñapátim̐ sùdhātúṃ yàjñapátiṃ devàyuvám || 12 ||', 'देवी॑रापो अग्रेगुवो अग्रेपु॒वोऽग्र॑ इ॒मम॒द्य य॒ज्ञं न॑य॒ताग्रे॑ य॒ज्ञप॑तिᳪ सु॒धातुं॑ य॒ज्ञप॑तिं देव॒युव॑म् ।। १२ ।।', 'Mantra 12b'],
    ['yùṣmā indró\'vṛṇīta vṛtràtūryé yū̀yamindrámavṛṇīdhvaṃ vṛtràtūryè prokṣítā stha |', 'यु॒ष्मा इन्द्रो॑ऽवृणीत वृत्र॒तूर्ये॑ यू॒यमिन्द्र॑मवृणीध्वं वृत्र॒तूर्ये॒ प्रोक्षि॑ता स्थ ।', 'Mantra 13a'],
    ['àgnayé tvā̀ juṣṭaṃ̀ prokṣā́myàgnīṣomā́bhyāṃ tvā̀ juṣṭaṃ̀ prokṣā́mi |', 'अ॒ग्नये॑ त्वा॒ जुष्टं॒ प्रोक्षा॑म्य॒ग्नीषोमा॑भ्यां त्वा॒ जुष्टं॒ प्रोक्षा॑मि ।', 'Mantra 13b'],
    ['daivyā́yà karmáṇe śundhadhvaṃ devayàjyāyaì yadvo\'śúddhāḥ parājàghnurìdaṃ vàstacchúndhāmi || 13 ||', 'दैव्या॑य॒ कर्म॑णे शुन्धध्वं देवय॒ज्यायै॒ यद्वोऽशु॑द्धाः पराज॒घ्नुरि॒दं व॒स्तच्छु॑न्धामि ।। १३ ।।', 'Mantra 13c'],
    ['śarmā̀syavádhūtàm̐ rakṣo\'vádhūtā̀ arā́tàyo \'dítyā̀stvagásì pratì tvādítirvettu | adrírasi vānaspàtyo grāvā́\'si pṛ̀thubúdhnàḥ pratì tvā\'dítyā̀stvagvéttu || 14 ||', 'शर्मा॒स्यव॑धूतᳪ॒ रक्षोऽव॑धूता॒ अरा॑त॒यो ऽदि॑त्या॒स्त्वग॑सि॒ प्रति॒ त्वादि॑तिर्वेत्तु । अद्रि॑रसि वानस्प॒त्यो ग्रावा॑ऽसि पृ॒थुबु॑ध्नः॒ प्रति॒ त्वाऽदि॑त्या॒स्त्वग्वे॑त्तु ।। १४ ।।', 'Mantra 14'],
];
